package constants;

public class Queries {

	
	
	public static String getQueryFirstPart(String tipoChiamata, String tableName) {
		String query = "";
		switch(tipoChiamata) {
		
		case "SALUTE_CONTRATTI_T601":
			query = "INSERT INTO "+tableName+" (ID_SIS_SORGENTE,NUM_DOC,OGGETTO_CONTR,ID_CONTRATTO_APCH,NUM_REVISIONE,INIZIO_VALIDITA,FINE_VALIDITA,DIVISA_ORDINE_ACQ,POS_DOC,TIPO_POSIZIONE,TESTO_BREVE,DATA_CONSEGNA,VAL_POS_DOC_EURO,IMPORTO_EM_DIVISA_INTERNA,VAL_POSIZIONE_DOCUMENTO,IMPORTO_EM_DIVISA_DOC,DIVISIONE,OGG_MERCEOLOGICO_CHIAVE_EST,UNITA_GESTORE,FORNITORE_ENI,DESCRIZIONE_ESTESA,TIPO_DOC_ACQUISTI,NUM_ACCORDO_QUADRO,SOCIETA,VAL_TESTATA_EURO,VAL_AMM_RESIDUA_EUR,VALORE_TESTATA,VAL_AMM_RESIDUA) with p (ID_SIS_SORGENTE,NUM_DOC,OGGETTO_CONTR,ID_CONTRATTO_APCH,NUM_REVISIONE,INIZIO_VALIDITA,FINE_VALIDITA,DIVISA_ORDINE_ACQ,POS_DOC,TIPO_POSIZIONE,TESTO_BREVE,DATA_CONSEGNA,VAL_POS_DOC_EURO,IMPORTO_EM_DIVISA_INTERNA,VAL_POSIZIONE_DOCUMENTO,IMPORTO_EM_DIVISA_DOC,DIVISIONE,OGG_MERCEOLOGICO_CHIAVE_EST,UNITA_GESTORE,FORNITORE_ENI,DESCRIZIONE_ESTESA,TIPO_DOC_ACQUISTI,NUM_ACCORDO_QUADRO,SOCIETA,VAL_TESTATA_EURO,VAL_AMM_RESIDUA_EUR,VALORE_TESTATA,VAL_AMM_RESIDUA) as (";
			break;	
		case "SALUTE_ORDINE_DI_LAVORO_T600":
			query = "INSERT INTO "+tableName+" (DATA_CREAZIONE_ODL,DESCRIZIONE_ESTESA,DES_CONT_ODL,DIVISA_ORDINE_ACQ,FORNITORE_ENI,ID_SIS_SORGENTE,INTESTAZIONE_ODL,NUM_DOC,NUM_DOC_ODL,POS_DOC_ODL,UNITA_GESTORE,VALORE_DESTCNT,VALORE_DESTCNT_EUR) with p (DATA_CREAZIONE_ODL,DESCRIZIONE_ESTESA,DES_CONT_ODL,DIVISA_ORDINE_ACQ,FORNITORE_ENI,ID_SIS_SORGENTE,INTESTAZIONE_ODL,NUM_DOC,NUM_DOC_ODL,POS_DOC_ODL,UNITA_GESTORE,VALORE_DESTCNT,VALORE_DESTCNT_EUR) as (";
			break;
		case "SALUTE_MDA_T602":
			query = "INSERT INTO "+tableName+" (DATA_REGCONT_MDA,DES_CONT_MDA,DIVISA_ORDINE_ACQ,ESERCIZIO_EM,ID_SIS_SORGENTE,MDA_STIMA,NUM_DOC_ODL,NUM_MDA,NUM_POS_DESCONT,POS_DOC_ODL,VAL_MDA_DIVDOC,VAL_MDA_EUR) with p (DATA_REGCONT_MDA,DES_CONT_MDA,DIVISA_ORDINE_ACQ,ESERCIZIO_EM,ID_SIS_SORGENTE,MDA_STIMA,NUM_DOC_ODL,NUM_MDA,NUM_POS_DESCONT,POS_DOC_ODL,VAL_MDA_DIVDOC,VAL_MDA_EUR) as (";
			break;
		case "SALUTE_FATTURE_T603":
			query = "INSERT INTO "+tableName+" (ID_SIS_SORGENTE,NUM_FATTURA,ESERC_FATTURA,POS_FATTURA,NUM_MDA,DES_CONT_FATT,NUM_FATTURA_EST,FLAG_ADD_SUCC,DATA_REG_FATTURA,IMPORTO_POS_FATTURA,DIVISA_FATTURA,VAL_POS_FATT_EUR,NUM_DOC_ODL,POS_DOC_ODL,CAMBI_FATTURA,CAT_POS_DOC_ACQUISTI,CENTRO_DI_COSTO,CENTRO_DI_RESPONSABILITA,CONTO_CO_GE,CHIAVE_INTERNA_OGG_IMM,CONTROLLING_AREA,CREDITORE_DIFFERENTE,DATA_INSERIMENTO,ELEMENTO_WBS,FLAG_DARE_AVERE,IMPORTO_DIVISA_DOC,NUM_BOLLA,NUM_CICLO,NUM_PRINCPL_CESPITE,NUM_PROGRESSIVO,NUM_SECONDARIO_CESPITE,NUM_SEGM_PROFIT,OGGETTO_DI_COSTO,PARTNAME,ORA_CREAZIONE,ORDINE_CO,PROFIT_CENTER,QUANTITA,SOCIETA,TESTO_POS_FATT,TIPO_DES_CONT,UM_ORDINE_ACQ,USER_FATTURA,TIPO_DOC_FATTURA,DATA_FATTURA) with p (ID_SIS_SORGENTE,NUM_FATTURA,ESERC_FATTURA,POS_FATTURA,NUM_MDA,DES_CONT_FATT,NUM_FATTURA_EST,FLAG_ADD_SUCC,DATA_REG_FATTURA,IMPORTO_POS_FATTURA,DIVISA_FATTURA,VAL_POS_FATT_EUR,NUM_DOC_ODL,POS_DOC_ODL,CAMBI_FATTURA,CAT_POS_DOC_ACQUISTI,CENTRO_DI_COSTO,CENTRO_DI_RESPONSABILITA,CONTO_CO_GE,CHIAVE_INTERNA_OGG_IMM,CONTROLLING_AREA,CREDITORE_DIFFERENTE,DATA_INSERIMENTO,ELEMENTO_WBS,FLAG_DARE_AVERE,IMPORTO_DIVISA_DOC,NUM_BOLLA,NUM_CICLO,NUM_PRINCPL_CESPITE,NUM_PROGRESSIVO,NUM_SECONDARIO_CESPITE,NUM_SEGM_PROFIT,OGGETTO_DI_COSTO,PARTNAME,ORA_CREAZIONE,ORDINE_CO,PROFIT_CENTER,QUANTITA,SOCIETA,TESTO_POS_FATT,TIPO_DES_CONT,UM_ORDINE_ACQ,USER_FATTURA,TIPO_DOC_FATTURA,DATA_FATTURA) as (";
			break;
		case "SALUTE_PARTNER_CONTRATTO_T605":
			query = "INSERT INTO "+tableName+" (COUNTER,DATA_INSERIMENTO,DESCRIZIONE_ESTESA,DES_RUOLO_PARTNER,FORNITORE_ENI,FORN_SOCIETARIO,FORN_SOCIETARIO_DESCR,ID_SIS_SORGENTE,NUM_DOC_ODL,RUOLO_PARTNER) with p (COUNTER,DATA_INSERIMENTO,DESCRIZIONE_ESTESA,DES_RUOLO_PARTNER,FORNITORE_ENI,FORN_SOCIETARIO,FORN_SOCIETARIO_DESCR,ID_SIS_SORGENTE,NUM_DOC_ODL,RUOLO_PARTNER) as (";
			break;
		case "SALUTE_ANAGRAFICA_PLANT_T606":
			query = "INSERT INTO "+tableName+" (AREA_VALORIZZAZIONE,DIVISIONE,DIVISIONE_LOCALITA,DIVISIONE_NAME,DIVISIONE_NAZIONE,ID_SIS_SORGENTE,INDIRIZZO,REGIONE,SOCIETA) with p (AREA_VALORIZZAZIONE,DIVISIONE,DIVISIONE_LOCALITA,DIVISIONE_NAME,DIVISIONE_NAZIONE,ID_SIS_SORGENTE,INDIRIZZO,REGIONE,SOCIETA) as (";
			break;
		case "SALUTE_ATTACHMENT_T607":
			query = "INSERT INTO "+tableName+" (EBELN, FILENAME, EXTENSION, ATTA_DATE, AUTHOR, FIELDKEY,ID,SERVIZIO) with p (EBELN, FILENAME, EXTENSION, ATTA_DATE, AUTHOR, FIELDKEY,ID,SERVIZIO) as (";
			break;
		case "SALUTE_ATTIVITA_CONTRATTO_T609":
			query = "INSERT INTO "+tableName+" (ID_SIS_SORGENTE, NUM_DOC, POS_DOC, NUM_PACCHETTO, NUM_RIGA, NOME_CATALOGO_PRESTAZIONI,DESCRIZIONE_MEDIA,QUANTITA,SOCICHIAVE_DIVISA,IMPORTO_TOTALE) with p (ID_SIS_SORGENTE, NUM_DOC, POS_DOC, NUM_PACCHETTO, NUM_RIGA, NOME_CATALOGO_PRESTAZIONI,DESCRIZIONE_MEDIA,QUANTITA,SOCICHIAVE_DIVISA,IMPORTO_TOTALE) as (";
			break;
		}
		return query;
	}
	
	
	
	public static String getSortingField(String tipoChiamata) {   // RIGUARDA SOLO LE CHIAMATE CHE RICHIEDONO LA DATA
		String sortingField = "";
		switch(tipoChiamata) {
		
		case "SALUTE_CONTRATTI_T601":
			sortingField = "INIZIO_VALIDITA";
			break;	
		case "SALUTE_ORDINE_DI_LAVORO_T600":
			sortingField = "DATA_CREAZIONE_ODL";
			break;
		case "SALUTE_FATTURE_T603": case "SALUTE_PARTNER_CONTRATTO_T605":
			sortingField = "DATA_INSERIMENTO";
			break;

		}
		return sortingField;
	}
	
	
	
	public static String[] getTrigger(String tipoChiamata) {  // CREA L'AUTO INCREMENT PER LA COLONNA ID DELLA TABELLA CONTRATTI
		String trigger = null;
		String seq = null;
		switch(tipoChiamata) {
		
		case "SALUTE_CONTRATTI_T601":
			trigger = "SALUTE_CONTRATTI_T601_BEFORE_INSERT";
			seq = "SALUTE_CONTRATTI_T601_SEQ";
			break;	
		}
		return new String[] {trigger,seq};
	}
}