package constants;

public enum TypeChiamata {
	
	SALUTE_CONTRATTI_T601,
	SALUTE_ORDINE_DI_LAVORO_T600,
	SALUTE_MDA_T602,
	SALUTE_FATTURE_T603,
	SALUTE_PARTNER_CONTRATTO_T605,
	SALUTE_ANAGRAFICA_PLANT_T606,
	SALUTE_ATTIVITA_CONTRATTO_T609,
}
